<?php

declare(strict_types=1);

return [
    ['GET', '', 'DashboardController@index', ['public' => false]],
    ['GET', 'dashboard/detalle/{slug}', 'DashboardController@detail', ['public' => false]],
    ['GET', 'login', 'AuthController@showLogin', ['public' => true]],
    ['POST', 'login', 'AuthController@login', ['public' => true]],
    ['GET', 'logout', 'AuthController@logout', ['public' => false]],

    ['GET', 'categorias', 'CategoryController@index', []],
    ['GET', 'categorias/crear', 'CategoryController@create', []],
    ['POST', 'categorias', 'CategoryController@store', []],
    ['GET', 'categorias/{id}/editar', 'CategoryController@edit', []],
    ['POST', 'categorias/{id}', 'CategoryController@update', []],
    ['POST', 'categorias/{id}/toggle', 'CategoryController@toggle', []],

    ['GET', 'productos', 'ProductController@index', []],
    ['GET', 'productos/crear', 'ProductController@create', []],
    ['POST', 'productos', 'ProductController@store', []],
    ['GET', 'productos/{id}/editar', 'ProductController@edit', []],
    ['POST', 'productos/{id}', 'ProductController@update', []],
    ['POST', 'productos/{id}/toggle', 'ProductController@toggle', []],
    ['POST', 'productos/{id}/imagenes/subir', 'ProductController@uploadImages', []],
    ['POST', 'productos/{id}/imagenes/reordenar', 'ProductController@reorderImages', []],
    ['POST', 'productos/{id}/imagenes/{img}/portada', 'ProductController@setCover', []],
    ['POST', 'productos/{id}/imagenes/{img}/eliminar', 'ProductController@deleteImage', []],
    ['POST', 'productos/{id}/imagenes/{img}/alt', 'ProductController@updateAltText', []],
    ['GET', 'productos/importar/ejemplo', 'ProductController@downloadImportTemplate', []],
    ['GET', 'productos/importar', 'ProductController@importForm', []],
    ['POST', 'productos/importar', 'ProductController@import', []],
    ['POST', 'productos/importar-masivo', 'ProductController@importMultiSheet', []],
    ['GET', 'combos', 'ComboController@index', []],
    ['GET', 'combos/crear', 'ComboController@create', []],
    ['POST', 'combos/guardar', 'ComboController@store', []],
    ['GET', 'combos/{id}/editar', 'ComboController@edit', []],
    ['POST', 'combos/{id}/actualizar', 'ComboController@update', []],
    ['POST', 'combos/{id}/eliminar', 'ComboController@destroy', []],
    ['POST', 'combos/{id}/toggle', 'ComboController@toggle', []],
    ['GET', 'stock-actual', 'StockController@index', []],
    ['POST', 'stock-actual/ajustar', 'StockController@adjust', []],

    ['GET', 'listas', 'PriceListController@index', []],
    ['GET', 'listas/generar', 'PriceListController@generateForm', []],
    ['POST', 'listas/preview', 'PriceListController@preview', []],
    ['POST', 'listas', 'PriceListController@store', []],
    ['GET', 'listas/{id}', 'PriceListController@show', []],
    ['GET', 'listas/{id}/pdf', 'PriceListController@downloadPdf', []],
    ['POST', 'listas/{id}/eliminar', 'PriceListController@delete', []],

    ['GET', 'clientes', 'ClientController@index', []],
    ['GET', 'clientes/crear', 'ClientController@create', []],
    ['POST', 'clientes', 'ClientController@store', []],
    ['GET', 'clientes/{id}/editar', 'ClientController@edit', []],
    ['POST', 'clientes/{id}', 'ClientController@update', []],
    ['POST', 'clientes/{id}/eliminar', 'ClientController@delete', []],

    ['GET', 'presupuestos', 'QuoteController@index', []],
    ['GET', 'presupuestos/crear', 'QuoteController@create', []],
    ['POST', 'presupuestos', 'QuoteController@store', []],
    ['GET', 'presupuestos/{id}', 'QuoteController@show', []],
    ['GET', 'presupuestos/{id}/editar', 'QuoteController@edit', []],
    ['POST', 'presupuestos/{id}', 'QuoteController@update', []],
    ['GET', 'presupuestos/{id}/pdf', 'QuoteController@downloadPdf', []],
    ['POST', 'presupuestos/{id}/eliminar', 'QuoteController@delete', []],
    ['POST', 'presupuestos/{id}/status', 'QuoteController@changeStatus', []],
    ['GET', 'presupuestos/{id}/enviar-mail', 'MailController@sendForm', []],
    ['POST', 'presupuestos/{id}/enviar-mail', 'MailController@send', []],
    ['GET', 'ventas', 'SaleController@index', []],
    ['GET', 'ventas/reportes', 'SaleController@reports', []],
    ['GET', 'ventas/exportar', 'SaleController@exportExcel', []],
    ['GET', 'ventas/reportes/exportar', 'SaleController@exportReportExcel', []],
    ['GET', 'ventas/{id}', 'SaleController@show', []],
    ['GET', 'ventas-ml', 'MercadoLibreController@index', []],
    ['GET', 'ventas-ml/crear', 'MercadoLibreController@create', []],
    ['POST', 'ventas-ml/guardar', 'MercadoLibreController@store', []],
    ['GET', 'ventas-ml/{id}/editar', 'MercadoLibreController@edit', []],
    ['POST', 'ventas-ml/{id}', 'MercadoLibreController@update', []],
    ['GET', 'ventas-ml/{id}', 'MercadoLibreController@show', []],

    ['POST', 'adjuntos/subir', 'AttachmentController@upload', []],
    ['GET', 'adjuntos/{id}/descargar', 'AttachmentController@download', []],
    ['GET', 'adjuntos/{id}/ver', 'AttachmentController@inline', []],
    ['POST', 'adjuntos/{id}/eliminar', 'AttachmentController@delete', []],

    ['GET', 'pedido-seiq', 'SeiqOrderController@index', []],
    ['GET', 'pedido-seiq/generar', 'SeiqOrderController@generate', []],
    ['POST', 'pedido-seiq', 'SeiqOrderController@store', []],
    ['GET', 'pedido-seiq/{id}', 'SeiqOrderController@show', []],
    ['GET', 'pedido-seiq/{id}/pdf', 'SeiqOrderController@downloadPdf', []],
    ['GET', 'pedido-seiq/{id}/pdf-precios', 'SeiqOrderController@downloadPdfWithPrices', []],
    ['POST', 'pedido-seiq/{id}/status', 'SeiqOrderController@changeStatus', []],
    ['POST', 'pedido-seiq/{id}/quotes-delivered', 'SeiqOrderController@markQuotesDelivered', []],
    ['GET', 'pedidos-proveedor', 'SeiqOrderController@index', []],
    ['GET', 'pedidos-proveedor/generar', 'SeiqOrderController@generate', []],
    ['POST', 'pedidos-proveedor', 'SeiqOrderController@store', []],
    ['GET', 'pedidos-proveedor/{id}', 'SeiqOrderController@show', []],
    ['GET', 'pedidos-proveedor/{id}/pdf', 'SeiqOrderController@downloadPdf', []],
    ['GET', 'pedidos-proveedor/{id}/pdf-precios', 'SeiqOrderController@downloadPdfWithPrices', []],
    ['POST', 'pedidos-proveedor/{id}/status', 'SeiqOrderController@changeStatus', []],
    ['POST', 'pedidos-proveedor/{id}/quotes-delivered', 'SeiqOrderController@markQuotesDelivered', []],

    ['GET', 'settings', 'SettingsController@index', []],
    ['POST', 'settings', 'SettingsController@update', []],
    ['GET', 'fix-stock', 'ToolsController@fixStock', []],
    ['POST', 'fix-stock/apply', 'ToolsController@fixStockApply', []],
    ['GET', 'sincronizacion', 'SyncController@index', []],
    ['POST', 'sincronizacion', 'SyncController@run', []],
    ['POST', 'sincronizacion/export-local', 'SyncController@exportLocalSql', []],
    ['POST', 'sincronizacion/import-local', 'SyncController@importSqlToLocal', []],

    ['GET', 'cuenta-corriente', 'AccountController@index', []],
    ['GET', 'cuenta-corriente/clientes', 'AccountController@clients', []],
    ['GET', 'cuenta-corriente/cliente/{id}', 'AccountController@clientDetail', []],
    ['GET', 'cuenta-corriente/proveedor/{id}', 'AccountController@supplierDetail', []],
    ['POST', 'cuenta-corriente/cobro', 'AccountController@registerCollection', []],
    ['POST', 'cuenta-corriente/pago-proveedor', 'AccountController@registerSupplierPayment', []],
    ['POST', 'cuenta-corriente/ajuste', 'AccountController@registerAdjustment', []],
    ['POST', 'cuenta-corriente/movimiento/{id}/eliminar', 'AccountController@deleteMovement', []],
    ['GET', 'cuenta-corriente/movimiento/{id}/editar', 'AccountController@editMovement', []],
    ['POST', 'cuenta-corriente/movimiento/{id}/actualizar', 'AccountController@updateMovement', []],
    ['GET', 'cuenta-corriente/cliente/{id}/pdf', 'AccountController@clientStatementPdf', []],
    ['GET', 'cuenta-corriente/proveedor/{id}/pdf', 'AccountController@supplierStatementPdf', []],

    ['GET', 'api/catalogo/productos/{slug}', 'ApiController@catalogProductDetail', ['public' => true]],
    ['GET', 'api/catalogo/productos', 'ApiController@catalogProducts', ['public' => true]],
    ['GET', 'api/catalogo/categorias', 'ApiController@catalogCategories', ['public' => true]],
    ['GET', 'api/productos/{id}/imagen/{img}/thumb', 'ApiController@serveProductThumb', ['public' => true]],
    ['GET', 'api/productos/{id}/imagen/{img}', 'ApiController@serveProductImage', ['public' => true]],
    ['GET', 'api/productos/buscar', 'ApiController@searchProducts', []],
    ['GET', 'api/productos/{id}/precio', 'ApiController@getProductPrice', []],
    ['GET', 'api/combos', 'ComboController@apiList', []],
    ['GET', 'api/combos/{id}', 'ComboController@apiShow', []],
    ['GET', 'api/combos/{id}/precio', 'ComboController@apiPrice', []],
    ['GET', 'api/categorias/{id}/productos', 'ApiController@getCategoryProducts', []],
    ['POST', 'api/clientes/crear', 'ClientController@apiStore', ['public' => false]],
    ['POST', 'api/pricing/preview', 'ApiController@previewPricing', []],
];
