<?php

declare(strict_types=1);

return [
    ['GET', '', 'DashboardController@index', ['public' => false]],
    ['GET', 'dashboard/detalle/{slug}', 'DashboardController@detail', ['public' => false]],
    ['GET', 'buscar', 'SearchController@index', []],
    ['GET', 'api/buscar', 'SearchController@apiSearch', []],
    ['GET', 'login', 'AuthController@showLogin', ['public' => true]],
    ['POST', 'login', 'AuthController@login', ['public' => true]],
    ['GET', 'logout', 'AuthController@logout', ['public' => false]],

    ['GET', 'categorias', 'CategoryController@index', []],
    ['GET', 'categorias/crear', 'CategoryController@create', []],
    ['POST', 'categorias', 'CategoryController@store', []],
    ['GET', 'categorias/{id}/editar', 'CategoryController@edit', []],
    ['POST', 'categorias/{id}', 'CategoryController@update', []],
    ['POST', 'categorias/{id}/toggle', 'CategoryController@toggle', []],

    ['GET', 'catalogo-visual', 'VisualCatalogController@index', []],
    ['GET', 'catalogo/generar-descripciones', 'CatalogDescriptionController@index', []],
    ['POST', 'catalogo/generar-descripciones/ejecutar', 'CatalogDescriptionController@execute', []],
    ['GET', 'productos', 'ProductController@index', []],
    ['GET', 'productos/crear', 'ProductController@create', []],
    ['POST', 'productos', 'ProductController@store', []],
    ['GET', 'productos/{id}/editar', 'ProductController@edit', []],
    ['POST', 'productos/{id}', 'ProductController@update', []],
    ['POST', 'productos/{id}/toggle', 'ProductController@toggle', []],
    ['POST', 'productos/{id}/imagenes/subir', 'ProductController@uploadImages', []],
    ['POST', 'api/productos/{id}/subir-imagen', 'ProductController@uploadCoverImage', []],
    ['POST', 'productos/{id}/imagenes/reordenar', 'ProductController@reorderImages', []],
    ['POST', 'productos/{id}/imagenes/{img}/portada', 'ProductController@setCover', []],
    ['POST', 'productos/{id}/imagenes/{img}/eliminar', 'ProductController@deleteImage', []],
    ['POST', 'productos/{id}/imagenes/{img}/alt', 'ProductController@updateAltText', []],
    ['GET', 'productos/importar/ejemplo', 'ProductController@downloadImportTemplate', []],
    ['GET', 'productos/importar', 'ProductController@importForm', []],
    ['POST', 'productos/importar', 'ProductController@import', []],
    ['POST', 'productos/importar-masivo', 'ProductController@importMultiSheet', []],
    ['GET', 'combos', 'ComboController@index', []],
    ['GET', 'combos/crear', 'ComboController@create', []],
    ['POST', 'combos/guardar', 'ComboController@store', []],
    ['GET', 'combos/{id}/editar', 'ComboController@edit', []],
    ['POST', 'combos/{id}/actualizar', 'ComboController@update', []],
    ['POST', 'combos/{id}/eliminar', 'ComboController@destroy', []],
    ['POST', 'combos/{id}/toggle', 'ComboController@toggle', []],
    ['GET', 'stock-actual', 'StockController@index', []],
    ['GET', 'stock/proyeccion', 'StockController@projection', []],
    ['GET', 'stock-actual/reposicion', 'StockController@reposicion', []],
    ['GET', 'stock/reorder-suggestion', 'StockController@reorderSuggestion', []],
    ['POST', 'stock/create-reorder', 'SeiqOrderController@createFromSuggestion', []],
    ['POST', 'stock-actual/ajustar', 'StockController@adjust', []],
    ['POST', 'stock/inline-adjust', 'StockController@inlineAdjust', []],

    ['GET', 'listas', 'PriceListController@index', []],
    ['GET', 'listas/generar', 'PriceListController@generateForm', []],
    ['POST', 'listas/preview', 'PriceListController@preview', []],
    ['POST', 'listas', 'PriceListController@store', []],
    ['GET', 'listas/{id}', 'PriceListController@show', []],
    ['GET', 'listas/{id}/pdf', 'PriceListController@downloadPdf', []],
    ['POST', 'listas/{id}/eliminar', 'PriceListController@delete', []],

    ['GET', 'clientes', 'ClientController@index', []],
    ['GET', 'clientes/crear', 'ClientController@create', []],
    ['POST', 'clientes', 'ClientController@store', []],
    ['GET', 'clientes/{id}', 'ClientController@show', []],
    ['GET', 'clientes/{id}/editar', 'ClientController@edit', []],
    ['POST', 'clientes/{id}', 'ClientController@update', []],
    ['POST', 'clientes/{id}/eliminar', 'ClientController@delete', []],

    ['GET', 'presupuestos', 'QuoteController@index', []],
    ['GET', 'presupuestos/crear', 'QuoteController@create', []],
    ['GET', 'presupuestos/rapido', 'QuoteController@quickCreate', []],
    ['POST', 'presupuestos/rapido', 'QuoteController@quickStore', []],
    ['POST', 'presupuestos', 'QuoteController@store', []],
    ['GET', 'presupuestos/{id}', 'QuoteController@show', []],
    ['GET', 'presupuestos/{id}/editar', 'QuoteController@edit', []],
    ['POST', 'presupuestos/{id}', 'QuoteController@update', []],
    ['GET', 'presupuestos/{id}/pdf', 'QuoteController@downloadPdf', []],
    ['POST', 'presupuestos/{id}/eliminar', 'QuoteController@delete', []],
    ['POST', 'presupuestos/{id}/status', 'QuoteController@changeStatus', []],
    ['POST', 'presupuestos/{id}/apply-credit', 'QuoteController@applyCredit', []],
    ['POST', 'presupuestos/{id}/remove-credit', 'QuoteController@removeCredit', []],
    ['POST', 'presupuestos/{id}/partial-delivery', 'QuoteController@partialDelivery', []],
    ['GET', 'presupuestos/{id}/enviar-mail', 'MailController@sendForm', []],
    ['POST', 'presupuestos/{id}/enviar-mail', 'MailController@send', []],
    ['GET', 'ventas', 'SaleController@index', []],
    ['GET', 'ventas/reportes', 'SaleController@reports', []],
    ['GET', 'ventas/exportar', 'SaleController@exportExcel', []],
    ['GET', 'ventas/reportes/exportar', 'SaleController@exportReportExcel', []],
    ['GET', 'ventas/{id}', 'SaleController@show', []],
    ['GET', 'pedidos-web', 'StoreOrderController@index', []],
    ['GET', 'pedidos-web/{id}', 'StoreOrderController@show', []],
    ['POST', 'pedidos-web/{id}/status', 'StoreOrderController@updateStatus', []],
    ['POST', 'pedidos-web/{id}/notas', 'StoreOrderController@updateAdminNotes', []],
    ['GET', 'ventas-ml', 'MercadoLibreController@index', []],
    ['GET', 'ventas-ml/crear', 'MercadoLibreController@create', []],
    ['POST', 'ventas-ml/guardar', 'MercadoLibreController@store', []],
    ['GET', 'ventas-ml/{id}/editar', 'MercadoLibreController@edit', []],
    ['POST', 'ventas-ml/{id}', 'MercadoLibreController@update', []],
    ['GET', 'ventas-ml/{id}', 'MercadoLibreController@show', []],

    ['GET', 'mercadolibre', 'MercadoLibreController@dashboard', []],
    ['GET', 'mercadolibre/conectar', 'MercadoLibreController@connect', []],
    ['GET', 'mercadolibre/callback', 'MercadoLibreController@callback', ['public' => true]],
    ['POST', 'mercadolibre/desconectar', 'MercadoLibreController@disconnect', []],
    ['GET', 'mercadolibre/listings', 'MercadoLibreController@listings', []],
    ['GET', 'mercadolibre/vincular-existentes', 'MercadoLibreController@linkExisting', []],
    ['POST', 'mercadolibre/vincular-existentes/guardar', 'MercadoLibreController@saveLinkExisting', []],
    ['GET', 'mercadolibre/listings/nueva', 'MercadoLibreController@newListing', []],
    ['POST', 'mercadolibre/listings', 'MercadoLibreController@storeListing', []],
    ['POST', 'mercadolibre/listings/sync-all', 'MercadoLibreController@syncAll', []],
    ['GET', 'mercadolibre/listings/{id}/editar', 'MercadoLibreController@editListing', []],
    ['POST', 'mercadolibre/listings/{id}', 'MercadoLibreController@updateListing', []],
    ['POST', 'mercadolibre/listings/{id}/publicar', 'MercadoLibreController@publishListing', []],
    ['POST', 'mercadolibre/listings/{id}/sync', 'MercadoLibreController@syncListing', []],
    ['POST', 'mercadolibre/listings/{id}/pausar', 'MercadoLibreController@pauseListing', []],
    ['POST', 'mercadolibre/listings/{id}/activar', 'MercadoLibreController@reactivateListing', []],
    ['POST', 'mercadolibre/listings/{id}/eliminar', 'MercadoLibreController@deleteListing', []],
    ['GET', 'mercadolibre/ordenes', 'MercadoLibreController@orders', []],
    ['POST', 'mercadolibre/ordenes/{order_id}/importar', 'MercadoLibreController@importOrder', []],
    ['GET', 'mercadolibre/publicacion-masiva', 'MercadoLibreController@bulkPublish', []],
    ['POST', 'mercadolibre/publicacion-masiva/ejecutar', 'MercadoLibreController@bulkPublishExecute', []],
    ['GET', 'mercadolibre/importar-imagenes', 'MercadoLibreController@importImages', []],
    ['POST', 'mercadolibre/importar-imagenes/ejecutar', 'MercadoLibreController@importImagesExecute', []],
    ['POST', 'mercadolibre/importar-imagenes/seiq-ejecutar', 'MercadoLibreController@importSeiqImagesExecute', []],
    ['GET', 'api/ml/precio-preview', 'MercadoLibreController@pricePreview', ['public' => true]],
    ['POST', 'api/ml/generar-descripcion', 'MercadoLibreController@generateDescription', ['public' => true]],
    ['POST', 'api/ml/guardar-descripcion-producto', 'MercadoLibreController@saveProductCatalogDescription', []],
    ['GET', 'api/ml/producto-imagenes', 'MercadoLibreController@productImageCount', []],
    ['GET', 'api/ml/sugerir-categoria', 'MercadoLibreController@suggestCategory', []],

    ['POST', 'adjuntos/subir', 'AttachmentController@upload', []],
    ['GET', 'adjuntos/{id}/descargar', 'AttachmentController@download', []],
    ['GET', 'adjuntos/{id}/ver', 'AttachmentController@inline', []],
    ['POST', 'adjuntos/{id}/eliminar', 'AttachmentController@delete', []],

    ['GET', 'pedidos-proveedor', 'SeiqOrderController@index', []],
    ['GET', 'pedidos-proveedor/generar', 'SeiqOrderController@generate', []],
    ['POST', 'pedidos-proveedor', 'SeiqOrderController@store', []],
    ['GET', 'pedidos-proveedor/{id}', 'SeiqOrderController@show', []],
    ['GET', 'pedidos-proveedor/{id}/pdf', 'SeiqOrderController@downloadPdf', []],
    ['GET', 'pedidos-proveedor/{id}/pdf-precios', 'SeiqOrderController@downloadPdfWithPrices', []],
    ['POST', 'pedidos-proveedor/{id}/status', 'SeiqOrderController@changeStatus', []],
    ['POST', 'pedidos-proveedor/{id}/recibir', 'SeiqOrderController@receiveOrder', []],
    ['GET', 'api/pedidos-proveedor/{id}/companions', 'SeiqOrderController@apiSentCompanions', []],
    ['POST', 'pedidos-proveedor/{id}/quotes-delivered', 'SeiqOrderController@markQuotesDelivered', []],
    ['POST', 'pedidos-proveedor/{id}/delete', 'SeiqOrderController@delete', []],
    ['POST', 'pedidos-proveedor/{id}/eliminar', 'SeiqOrderController@delete', []],

    ['GET', 'settings', 'SettingsController@index', []],
    ['POST', 'settings', 'SettingsController@update', []],
    ['GET', 'fix-stock', 'ToolsController@fixStock', []],
    ['POST', 'fix-stock/apply', 'ToolsController@fixStockApply', []],
    ['GET', 'tools/reconciliar-stock', 'ToolsController@reconcileStock', []],
    ['POST', 'tools/reconciliar-stock/aplicar', 'ToolsController@applyReconciliation', []],
    ['GET', 'sincronizacion', 'SyncController@index', []],
    ['POST', 'sincronizacion', 'SyncController@run', []],
    ['POST', 'sincronizacion/export-local', 'SyncController@exportLocalSql', []],
    ['POST', 'sincronizacion/import-local', 'SyncController@importSqlToLocal', []],

    ['GET', 'cuenta-corriente', 'AccountController@index', []],
    ['GET', 'cuenta-corriente/clientes', 'AccountController@clients', []],
    ['GET', 'cuenta-corriente/cliente/{id}', 'AccountController@clientDetail', []],
    ['GET', 'cuenta-corriente/proveedor/{id}', 'AccountController@supplierDetail', []],
    ['POST', 'cuenta-corriente/cobro', 'AccountController@registerCollection', []],
    ['POST', 'cuenta-corriente/pago-rapido', 'AccountController@quickPayment', []],
    ['POST', 'cuenta-corriente/pago-proveedor', 'AccountController@registerSupplierPayment', []],
    ['POST', 'cuenta-corriente/ajuste', 'AccountController@registerAdjustment', []],
    ['POST', 'cuenta-corriente/movimiento/{id}/eliminar', 'AccountController@deleteMovement', []],
    ['GET', 'cuenta-corriente/movimiento/{id}/editar', 'AccountController@editMovement', []],
    ['POST', 'cuenta-corriente/movimiento/{id}/actualizar', 'AccountController@updateMovement', []],
    ['GET', 'cuenta-corriente/cliente/{id}/pdf', 'AccountController@clientStatementPdf', []],
    ['GET', 'cuenta-corriente/proveedor/{id}/pdf', 'AccountController@supplierStatementPdf', []],

    ['GET', 'api/presupuestos/{id}/items-explotados', 'QuoteController@apiItemsExplotados', ['public' => true]],
    ['GET', 'api/catalogo/productos/{slug}', 'ApiController@catalogProductDetail', ['public' => true]],
    ['GET', 'api/catalogo/productos', 'ApiController@catalogProducts', ['public' => true]],
    ['GET', 'api/catalogo/categorias', 'ApiController@catalogCategories', ['public' => true]],
    ['GET', 'api/catalogo/destacados', 'ApiController@catalogFeatured', ['public' => true]],
    ['GET', 'api/catalogo/nuevos', 'ApiController@catalogNew', ['public' => true]],
    ['GET', 'api/catalogo/mas-vendidos', 'ApiController@catalogBestsellers', ['public' => true]],
    ['GET', 'api/catalogo/categorias-tienda', 'ApiController@catalogStoreCategories', ['public' => true]],
    ['GET', 'api/catalogo/categoria/{slug}', 'ApiController@catalogByStoreCategory', ['public' => true]],
    ['POST', 'api/tienda/pedido', 'StoreOrderController@createOrder', ['public' => true]],
    ['GET', 'api/tienda/pedidos', 'StoreOrderController@getOrdersByPhone', ['public' => true]],
    ['GET', 'api/tienda/pedidos/{order_number}', 'StoreOrderController@getOrder', ['public' => true]],
    ['GET', 'producto-imagen/{product_id}/{filename}', 'ApiController@serveProductImage', ['public' => true]],
    ['GET', 'api/productos/{id}/imagen/{img}/thumb', 'ApiController@serveProductThumb', ['public' => true]],
    ['GET', 'api/productos/{id}/imagen/{img}', 'ApiController@serveProductImageById', ['public' => true]],
    ['GET', 'api/productos/buscar', 'ApiController@searchProducts', []],
    ['GET', 'api/productos/{id}/precio', 'ApiController@getProductPrice', []],
    ['GET', 'api/combos', 'ComboController@apiList', []],
    ['GET', 'api/combos/buscar', 'ComboController@apiSearch', []],
    ['GET', 'api/combos/{id}', 'ComboController@apiShow', []],
    ['GET', 'api/combos/{id}/precio', 'ComboController@apiPrice', []],
    ['GET', 'api/categorias/{id}/productos', 'ApiController@getCategoryProducts', []],
    ['GET', 'api/clientes/{id}/markup', 'ApiController@clientMarkup', []],
    ['POST', 'api/clientes/crear', 'ClientController@apiStore', ['public' => false]],
    ['POST', 'api/pricing/preview', 'ApiController@previewPricing', []],
];
